# Welcome to the PendulumOscillatorForHeliumBalloon configuration settings
#
# This is a Demo-Plugin for HeliumBalloon
# to demonstrate how you can implement a Custom Oscillator
# by using the BalloonOscillatorCreateEvent.
# It adds a pendulum (like a children's swing) as oscillator.
#
# Get the HeliumBalloon plugin from
#   https://www.spigotmc.org/resources/heliumballoon.95902
#
#
# In this example we use the "oscillatorHint" attribute of the rule
# to mark our custom oscillator
#
# The following configuration is loaded as part of the Balloon Config.
# It offers a mincart loaded ith an emerald
#
# Please adjust the coordinates to your need.
#


rules:
    pendulum:
       oscillatorHint: "pendulum"
       minecartDelay: 0
       
templates:
    pendulum:
        rule: pendulum
        oscillating: true
        minecart:
           loadOffset: 30
           load:
               material: EMERALD_BLOCK

rotators:
    pendulum:
        template: pendulum
        world: world
        x: -160
        y: 89
        z: 330
