name: PendulumOscillatorForHeliumBalloon
version: 2.0
description: A demo howto make custom oscillators for HeliumBalloon
author: Kirastur
website: https://github.com/Kirastur/PendulumOscillatorForHeliumBalloon


api-version: 1.19
load: POSTWORLD
main: de.polarwolf.pendulumoscillator.Main
depend: [HeliumBalloon]
